# This is a basic workflow to help you get started with Actions

name: publish

on:
  release:
    branches:
      - main
    types: # This configuration does not affect the page_build event above
      - created
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Prepare version
        id: prepare_version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cat "${GITHUB_REF##refs/tags/}"
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=version::${TAG_NAME}"
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      # Runs a single command using the runners shell
      - name: build
        run: npm i && npm run build
      - name: version & publish
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            cat "${{steps.prepare_version.outputs.version}}"
            npm config set git-tag-version false
            npm version "${{steps.prepare_version.outputs.version}}"
            npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
